
title: Famirol
email: info.famirol@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Familien-Wanderungen in Tirol mit den Öffis
search: true

# Build settings
markdown: kramdown

# Outputting
permalink: /:categories/:title/
paginate: 15 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
